# Generated by Django 4.0.1 on 2022-02-07 12:59
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
        ),
    ]
