# Generated by Django 4.0.1 on 2022-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_cadastrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
