# Generated by Django 4.0.1 on 2022-02-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0004_produto_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
