# Generated by Django 4.0.1 on 2022-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
