# Generated by Django 4.0.1 on 2022-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='ProdutoPadrão.png', null=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
